### ISSUE TITLE
English

### ISSUE THREAD

**Issue by Kukks** [ricardodalarme/CryBits#4]
Please consider translating the code comments to English as it is incredibly harder for new contributors to jump in. Thee codebase already uses English so I don't see why it should be different.

**Comment by ricardodalarme** [comment]
Thank you for the tip! The reason I haven't translated the comments yet is because there are a lot of them and that gives me a lot of work. As soon as I release a really stable version to develop a game, I promise that I will translate the comments. One thing I'm going to start doing right now is to write the commits messages in English. Sincerely, Ricardo.
